{
 "title": "GraalVM",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Streaming test",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_Histogram_seconds_sum / streaming_Histogram_seconds_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GRPC requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grpc_requests_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "AES-En-/Decryption Average Seconds / Method-Call",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "useAES_Duration_Histogram_seconds_sum / useAES_Duration_Histogram_seconds_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "objectify_string Average Seconds / Method-Call",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "objectify_String_Histogram_seconds_sum / objectify_String_Histogram_seconds_count",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}